### ISSUE TITLE
Document animal data access

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/Douglas_User_Documentation#13]
Discuss here.

- [ ] do we automate brukraw conversion?

**Comment by jeremie-fouquet** [comment]
I think it's a good idea to have automated conversion to nifti via brkraw, at least as an option.

Current groups want their data either as raw Bruker data or as nifti (about 50/50). The conversion to nifti is currently done manually with Axel's APMConvert2FSL script, which is based on pvconv.pl. I think it's worth it to move to brkraw, and to have some kind of automated conversion as an option.

**Comment by jeremie-fouquet** [comment]
Data access is highly heterogeneous right now. It varies from people getting raw bruker data on the bruker computer while it is still there, to me converting to nifti and uploading to a shared cloud service.

**Comment by jeremie-fouquet** [comment]
@gdevenyi , do you think it is a good idea to grant access to the CIC servers to all Bruker users who want to access their data?

It would help to uniformize data access.

**Comment by gdevenyi** [comment]
I definitely think we should be consolidating into a single access method (or perhaps two, for the cases where you do all sample handling and data collection and send it off to some external person somewhere). Uses should have accounts on the CIC system as well.

I also definitely think we should streamline into a Bruker+brkraw conversion (possibly to BIDS).

For now, can we attempt the minimum bit of standardization of describing how to access the raw bruker scans via rsync to the scanner?

**Comment by jeremie-fouquet** [comment]
Ok, yes. Does it make sense to have a `/home/cic/dicom/transfers/` equivalent for the animal side? This is where I would redirect users for data access, and where I would eventually perform brkraw conversion.

Also, can you create CIC accounts for users outside of the Douglas (e.g., from other McGill departments?)?

**Comment by gdevenyi** [comment]
> Does it make sense to have a /home/cic/dicom/transfers/ equivalent for the animal side?

Definitely, I'm thinking about how to streamline the human/animal into a single location, and automating conversion for both cases as well.

> Also, can you create CIC accounts for users outside of the Douglas (e.g., from other McGill departments?)?

Yes, we just need requests from the actual PI/person in charge of the money in case we need to issue bills at some point (for storage/cold storage retrieval).

**Comment by jeremie-fouquet** [comment]
Great. I'd be ready to implement this `/home/cic/dicom/transfers/` equivalent pretty much when you are.

Depending on the expected time scale, I could either wait for this implementation before writing the doc, or write a first quick draft describing how to currently access the raw Bruker scans via rsync to the scanner console.

**Comment by gdevenyi** [comment]
Let's go with documenting the current process, as you're aware there are a few deficiencies still in the conversion I'd like to sort out.
