### ISSUE TITLE
Configure readthedocs to handle custom domain

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/Douglas_User_Documentation#3]
https://docs.readthedocs.io/en/stable/custom_domains.html

So we can use docs.douglasneuroinformatics.ca

**Comment by gdevenyi** [comment]
I can't do this myself because readthedocs does not understand github groups

**Comment by surchs** [comment]
I'm not sure what needs to happen here @gdevenyi. Is there something you'd like me to do?

**Comment by gdevenyi** [comment]
I can do 1. because of how readthedocs is setup I can't access the admin interface for this repo, so could you please do 2-4 for docs.douglasneuroinformatics.ca

![image](https://user-images.githubusercontent.com/3001850/121192095-934eb780-c83a-11eb-8c89-696ba4ee85e6.png)

**Comment by surchs** [comment]
![image](https://user-images.githubusercontent.com/1302022/121193680-0a388000-c83c-11eb-82a1-a48b65e5498d.png)
is now the "canonical" domain. How do we check that the change works?

**Comment by gdevenyi** [comment]
I have to make my settings change, and then docs.douglasneuroinformatics.ca should just "be the domain"

**Comment by gdevenyi** [comment]
Changed, 15 minute clearance on the DNS.

**Comment by surchs** [comment]
https://douglas-user-documentation.readthedocs.io/ resolves for me. Closing
