### ISSUE TITLE
More details in section "using the DNP system"

### ISSUE THREAD

**Issue by LuceroGG** [DouglasNeuroInformatics/Douglas_User_Documentation#34]
In this section, the acronym DNP appears for the first time with no previous reference of its meaning (though it can be inferred, is worth being explicit before documentation grows).
I would suggest enriching the section about playing nice, perhaps with links to understand how to interpret the output obtained when using them.
It may be worth listing command who -q (?)
Thanks

**Comment by gdevenyi** [comment]
Thanks.

**Comment by surchs** [comment]
@all-contributors please add @LuceroGG for userTesting, ideas
