### ISSUE TITLE
Files system layout - could be clearer at a glance?

### ISSUE THREAD

**Issue by devdinie** [DouglasNeuroInformatics/Douglas_User_Documentation#36]
The description is very clear but It maybe helpful to new users if the the sections "file system layout"  is clearer visually. Giving this idea at a glance will ensure that they don't try accessing or using the directories or paths that are not usually preferred. It will also be easier to recall if contents from this section are mentioned elsewhere in the document.

**Comment by surchs** [comment]
@all-contributors please add @devdinie for ideas
